/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package aeson-1.4.4.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.4.4.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_aeson */

/* package Diff-0.3.4 */
#ifndef VERSION_Diff
#define VERSION_Diff "0.3.4"
#endif /* VERSION_Diff */
#ifndef MIN_VERSION_Diff
#define MIN_VERSION_Diff(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 4)
#endif /* MIN_VERSION_Diff */

/* package QuickCheck-2.13.1 */
#ifndef VERSION_QuickCheck
#define VERSION_QuickCheck "2.13.1"
#endif /* VERSION_QuickCheck */
#ifndef MIN_VERSION_QuickCheck
#define MIN_VERSION_QuickCheck(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  13 || \
  (major1) == 2 && (major2) == 13 && (minor) <= 1)
#endif /* MIN_VERSION_QuickCheck */

/* package aeson-1.4.4.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.4.4.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_aeson */

/* package attoparsec-0.13.2.2 */
#ifndef VERSION_attoparsec
#define VERSION_attoparsec "0.13.2.2"
#endif /* VERSION_attoparsec */
#ifndef MIN_VERSION_attoparsec
#define MIN_VERSION_attoparsec(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_attoparsec */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package base-compat-0.10.5 */
#ifndef VERSION_base_compat
#define VERSION_base_compat "0.10.5"
#endif /* VERSION_base_compat */
#ifndef MIN_VERSION_base_compat
#define MIN_VERSION_base_compat(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 5)
#endif /* MIN_VERSION_base_compat */

/* package base-orphans-0.8.1 */
#ifndef VERSION_base_orphans
#define VERSION_base_orphans "0.8.1"
#endif /* VERSION_base_orphans */
#ifndef MIN_VERSION_base_orphans
#define MIN_VERSION_base_orphans(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 1)
#endif /* MIN_VERSION_base_orphans */

/* package base16-bytestring-0.1.1.6 */
#ifndef VERSION_base16_bytestring
#define VERSION_base16_bytestring "0.1.1.6"
#endif /* VERSION_base16_bytestring */
#ifndef MIN_VERSION_base16_bytestring
#define MIN_VERSION_base16_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_base16_bytestring */

/* package bytestring-0.10.8.2 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.8.2"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 8)
#endif /* MIN_VERSION_bytestring */

/* package containers-0.6.0.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.0.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_containers */

/* package directory-1.3.3.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.3.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_directory */

/* package dlist-0.8.0.6 */
#ifndef VERSION_dlist
#define VERSION_dlist "0.8.0.6"
#endif /* VERSION_dlist */
#ifndef MIN_VERSION_dlist
#define MIN_VERSION_dlist(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_dlist */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package generic-deriving-1.12.4 */
#ifndef VERSION_generic_deriving
#define VERSION_generic_deriving "1.12.4"
#endif /* VERSION_generic_deriving */
#ifndef MIN_VERSION_generic_deriving
#define MIN_VERSION_generic_deriving(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  12 || \
  (major1) == 1 && (major2) == 12 && (minor) <= 4)
#endif /* MIN_VERSION_generic_deriving */

/* package ghc-prim-0.5.3 */
#ifndef VERSION_ghc_prim
#define VERSION_ghc_prim "0.5.3"
#endif /* VERSION_ghc_prim */
#ifndef MIN_VERSION_ghc_prim
#define MIN_VERSION_ghc_prim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_ghc_prim */

/* package hashable-1.3.0.0 */
#ifndef VERSION_hashable
#define VERSION_hashable "1.3.0.0"
#endif /* VERSION_hashable */
#ifndef MIN_VERSION_hashable
#define MIN_VERSION_hashable(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_hashable */

/* package hashable-time-0.2.0.2 */
#ifndef VERSION_hashable_time
#define VERSION_hashable_time "0.2.0.2"
#endif /* VERSION_hashable_time */
#ifndef MIN_VERSION_hashable_time
#define MIN_VERSION_hashable_time(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_hashable_time */

/* package integer-logarithms-1.0.3 */
#ifndef VERSION_integer_logarithms
#define VERSION_integer_logarithms "1.0.3"
#endif /* VERSION_integer_logarithms */
#ifndef MIN_VERSION_integer_logarithms
#define MIN_VERSION_integer_logarithms(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_integer_logarithms */

/* package quickcheck-instances-0.3.21 */
#ifndef VERSION_quickcheck_instances
#define VERSION_quickcheck_instances "0.3.21"
#endif /* VERSION_quickcheck_instances */
#ifndef MIN_VERSION_quickcheck_instances
#define MIN_VERSION_quickcheck_instances(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 21)
#endif /* MIN_VERSION_quickcheck_instances */

/* package scientific-0.3.6.2 */
#ifndef VERSION_scientific
#define VERSION_scientific "0.3.6.2"
#endif /* VERSION_scientific */
#ifndef MIN_VERSION_scientific
#define MIN_VERSION_scientific(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 6)
#endif /* MIN_VERSION_scientific */

/* package tagged-0.8.6 */
#ifndef VERSION_tagged
#define VERSION_tagged "0.8.6"
#endif /* VERSION_tagged */
#ifndef MIN_VERSION_tagged
#define MIN_VERSION_tagged(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 6)
#endif /* MIN_VERSION_tagged */

/* package tasty-1.2.3 */
#ifndef VERSION_tasty
#define VERSION_tasty "1.2.3"
#endif /* VERSION_tasty */
#ifndef MIN_VERSION_tasty
#define MIN_VERSION_tasty(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_tasty */

/* package tasty-golden-2.3.2 */
#ifndef VERSION_tasty_golden
#define VERSION_tasty_golden "2.3.2"
#endif /* VERSION_tasty_golden */
#ifndef MIN_VERSION_tasty_golden
#define MIN_VERSION_tasty_golden(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 2)
#endif /* MIN_VERSION_tasty_golden */

/* package tasty-hunit-0.10.0.2 */
#ifndef VERSION_tasty_hunit
#define VERSION_tasty_hunit "0.10.0.2"
#endif /* VERSION_tasty_hunit */
#ifndef MIN_VERSION_tasty_hunit
#define MIN_VERSION_tasty_hunit(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_tasty_hunit */

/* package tasty-quickcheck-0.10.1 */
#ifndef VERSION_tasty_quickcheck
#define VERSION_tasty_quickcheck "0.10.1"
#endif /* VERSION_tasty_quickcheck */
#ifndef MIN_VERSION_tasty_quickcheck
#define MIN_VERSION_tasty_quickcheck(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 1)
#endif /* MIN_VERSION_tasty_quickcheck */

/* package template-haskell-2.14.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.14.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  14 || \
  (major1) == 2 && (major2) == 14 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* package text-1.2.3.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package time-1.8.0.2 */
#ifndef VERSION_time
#define VERSION_time "1.8.0.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_time */

/* package time-compat-1.9.2.2 */
#ifndef VERSION_time_compat
#define VERSION_time_compat "1.9.2.2"
#endif /* VERSION_time_compat */
#ifndef MIN_VERSION_time_compat
#define MIN_VERSION_time_compat(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  9 || \
  (major1) == 1 && (major2) == 9 && (minor) <= 2)
#endif /* MIN_VERSION_time_compat */

/* package unordered-containers-0.2.10.0 */
#ifndef VERSION_unordered_containers
#define VERSION_unordered_containers "0.2.10.0"
#endif /* VERSION_unordered_containers */
#ifndef MIN_VERSION_unordered_containers
#define MIN_VERSION_unordered_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_unordered_containers */

/* package uuid-types-1.0.3 */
#ifndef VERSION_uuid_types
#define VERSION_uuid_types "1.0.3"
#endif /* VERSION_uuid_types */
#ifndef MIN_VERSION_uuid_types
#define MIN_VERSION_uuid_types(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_uuid_types */

/* package vector-0.12.0.3 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.0.3"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_vector */

/* tool gcc-4.2.1 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "4.2.1"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  2 || \
  (major1) == 4 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "aeson-1.4.4.0-inplace-tests"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.4.4.0"
#endif /* CURRENT_PACKAGE_VERSION */
